<?php


/**
 * This class defines the structure of the 'fast_click' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:13 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FastClickTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FastClickTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('fast_click');
		$this->setPhpName('FastClick');
		$this->setClassname('FastClick');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('TIME', 'Time', 'INTEGER', true, 11, null);
		$this->addColumn('UA_ID', 'UaId', 'INTEGER', true, 10, null);
		$this->addColumn('A_HASH', 'AHash', 'VARCHAR', true, 8, null);
		$this->addColumn('AD_ID', 'AdId', 'INTEGER', true, 10, null);
		$this->addColumn('USER_ID', 'UserId', 'INTEGER', true, 10, null);
		$this->addColumn('ADVERT_ID', 'AdvertId', 'INTEGER', true, 10, null);
		$this->addColumn('IP', 'Ip', 'INTEGER', false, 10, null);
		$this->addColumn('SUBNET', 'Subnet', 'INTEGER', false, 10, null);
		$this->addColumn('REF', 'Ref', 'VARCHAR', true, 100, null);
		$this->addColumn('LAST_CLICK_TIME', 'LastClickTime', 'INTEGER', false, 11, null);
		$this->addColumn('NO_COOKIE', 'NoCookie', 'INTEGER', true, 1, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // FastClickTableMap
