<?php


/**
 * This class defines the structure of the 'outgoing_funds' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:13 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class OutgoingFundsTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.OutgoingFundsTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('outgoing_funds');
		$this->setPhpName('OutgoingFunds');
		$this->setClassname('OutgoingFunds');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('TIME', 'Time', 'TIMESTAMP', true, null, null);
		$this->addColumn('APPROVED_AT', 'ApprovedAt', 'TIMESTAMP', false, null, null);
		$this->addForeignKey('ACCOUNT_ID', 'AccountId', 'INTEGER', 'account', 'ID', true, 11, null);
		$this->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'user', 'ID', true, 11, null);
		$this->addColumn('AMOUNT', 'Amount', 'INTEGER', true, 7, null);
		$this->addColumn('MONEY', 'Money', 'INTEGER', true, 7, null);
		$this->addColumn('STATUS', 'Status', 'INTEGER', true, 3, null);
		$this->addColumn('CURRENCY', 'Currency', 'INTEGER', true, 3, null);
		$this->addColumn('EMONEY_ID', 'EmoneyId', 'VARCHAR', true, 300, null);
		$this->addColumn('COMMENT', 'Comment', 'LONGVARCHAR', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Account', 'Account', RelationMap::MANY_TO_ONE, array('account_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('User', 'User', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // OutgoingFundsTableMap
