<?php


/**
 * This class defines the structure of the 'stat_auditory_daily' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:13 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class StatAuditoryDailyTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.StatAuditoryDailyTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('stat_auditory_daily');
		$this->setPhpName('StatAuditoryDaily');
		$this->setClassname('StatAuditoryDaily');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('DATE', 'Date', 'DATE', true, null, null);
		$this->addColumn('USERS', 'Users', 'INTEGER', true, 11, null);
		$this->addColumn('AGENTS', 'Agents', 'INTEGER', true, 11, null);
		$this->addColumn('ADVERTS', 'Adverts', 'INTEGER', true, 11, null);
		$this->addColumn('ACTIVE_AGENTS', 'ActiveAgents', 'INTEGER', true, 11, null);
		$this->addColumn('ACTIVE_ADVERTS', 'ActiveAdverts', 'INTEGER', true, 11, null);
		$this->addColumn('NEW_USERS', 'NewUsers', 'INTEGER', true, 11, null);
		$this->addColumn('NEW_AGENTS', 'NewAgents', 'INTEGER', true, 11, null);
		$this->addColumn('NEW_ADVERTS', 'NewAdverts', 'INTEGER', true, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // StatAuditoryDailyTableMap
