<?php


/**
 * This class defines the structure of the 'stat_activity_daily' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:13 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class StatActivityDailyTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.StatActivityDailyTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('stat_activity_daily');
		$this->setPhpName('StatActivityDaily');
		$this->setClassname('StatActivityDaily');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('DATE', 'Date', 'INTEGER', true, 11, null);
		$this->addColumn('SHARES', 'Shares', 'INTEGER', true, 11, null);
		$this->addColumn('CLICKS', 'Clicks', 'INTEGER', true, 11, null);
		$this->addColumn('CLICKS_SHARES', 'ClicksShares', 'FLOAT', true, null, null);
		$this->addColumn('AVG_SHARE_AGENTS', 'AvgShareAgents', 'FLOAT', true, null, null);
		$this->addColumn('AVG_SHARE_ACTIVE_AGENTS', 'AvgShareActiveAgents', 'FLOAT', true, null, null);
		$this->addColumn('AVG_CLICKS_AGENTS', 'AvgClicksAgents', 'FLOAT', true, null, null);
		$this->addColumn('AVG_CLICKS_ACTIVE_AGENTS', 'AvgClicksActiveAgents', 'FLOAT', true, null, null);
		$this->addColumn('ADVERTISE_CATALOG', 'AdvertiseCatalog', 'FLOAT', true, null, null);
		$this->addColumn('ACTIVE_ADVERTISE', 'ActiveAdvertise', 'FLOAT', true, null, null);
		$this->addColumn('ACTIVE_UNACTIVE_ADVERTISE', 'ActiveUnactiveAdvertise', 'FLOAT', true, null, null);
		$this->addColumn('ADVERTISE_SHARES', 'AdvertiseShares', 'FLOAT', true, null, null);
		$this->addColumn('ADVERTISE_CLICKS', 'AdvertiseClicks', 'FLOAT', true, null, null);
		$this->addColumn('ACTIVE_ADVERTISE_SHARES', 'ActiveAdvertiseShares', 'FLOAT', true, null, null);
		$this->addColumn('ACTIVE_ADVERTISE_CLICKS', 'ActiveAdvertiseClicks', 'FLOAT', true, null, null);
		$this->addColumn('ADVERTISE_ADVERTS', 'AdvertiseAdverts', 'FLOAT', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // StatActivityDailyTableMap
