<?php


/**
 * This class defines the structure of the 'stat_global_hours' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:14 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class StatGlobalHoursTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.StatGlobalHoursTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('stat_global_hours');
		$this->setPhpName('StatGlobalHours');
		$this->setClassname('StatGlobalHours');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('DATE_HOUR', 'DateHour', 'TIMESTAMP', true, null, null);
		$this->addColumn('CLICKS', 'Clicks', 'INTEGER', true, 11, null);
		$this->addColumn('ACTIONS', 'Actions', 'INTEGER', true, 11, null);
		$this->addColumn('POINTS', 'Points', 'INTEGER', true, 11, null);
		$this->addColumn('FEE', 'Fee', 'INTEGER', true, 7, null);
		$this->addColumn('INVALID_CLICKS', 'InvalidClicks', 'INTEGER', true, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // StatGlobalHoursTableMap
