<?php


/**
 * This class defines the structure of the 'transaction' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:14 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TransactionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TransactionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('transaction');
		$this->setPhpName('Transaction');
		$this->setClassname('Transaction');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', true, null, null);
		$this->addColumn('POINTS', 'Points', 'INTEGER', true, 7, null);
		$this->addColumn('AMOUNT', 'Amount', 'INTEGER', true, 7, null);
		$this->addColumn('FEE', 'Fee', 'INTEGER', true, 7, null);
		$this->addColumn('FROM', 'From', 'INTEGER', true, 11, null);
		$this->addColumn('TO', 'To', 'INTEGER', true, 11, null);
		$this->addColumn('FROM_USER', 'FromUser', 'INTEGER', true, 11, null);
		$this->addColumn('TO_USER', 'ToUser', 'INTEGER', true, 11, null);
		$this->addColumn('INVOICE_ID', 'InvoiceId', 'INTEGER', true, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // TransactionTableMap
