<?php


/**
 * This class defines the structure of the 'user_advertise' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:14 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UserAdvertiseTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UserAdvertiseTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('user_advertise');
		$this->setPhpName('UserAdvertise');
		$this->setClassname('UserAdvertise');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'user', 'ID', true, 11, null);
		$this->addColumn('ADVERT_ID', 'AdvertId', 'INTEGER', true, 11, null);
		$this->addForeignKey('ADVERTISE_ID', 'AdvertiseId', 'INTEGER', 'advertise', 'ID', true, 11, null);
		$this->addColumn('STATUS', 'Status', 'INTEGER', true, 3, null);
		$this->addColumn('URL', 'Url', 'VARCHAR', true, 300, null);
		$this->addColumn('SECRET', 'Secret', 'VARCHAR', true, 50, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', true, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('User', 'User', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Advertise', 'Advertise', RelationMap::MANY_TO_ONE, array('advertise_id' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Action', 'Action', RelationMap::ONE_TO_MANY, array('id' => 'ua_id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('StatAgentDaily', 'StatAgentDaily', RelationMap::ONE_TO_MANY, array('id' => 'ua_id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // UserAdvertiseTableMap
