<?php

/**
 * Base static class for performing query and update operations on the 'stat_money_daily' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:14 2011
 *
 * @package    lib.model.om
 */
abstract class BaseStatMoneyDailyPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'stat_money_daily';

	/** the related Propel class for this table */
	const OM_CLASS = 'StatMoneyDaily';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.StatMoneyDaily';

	/** the related TableMap class for this table */
	const TM_CLASS = 'StatMoneyDailyTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 29;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'stat_money_daily.ID';

	/** the column name for the DATE field */
	const DATE = 'stat_money_daily.DATE';

	/** the column name for the TURNOVER field */
	const TURNOVER = 'stat_money_daily.TURNOVER';

	/** the column name for the TURNOVER_POINTS field */
	const TURNOVER_POINTS = 'stat_money_daily.TURNOVER_POINTS';

	/** the column name for the REVENUE field */
	const REVENUE = 'stat_money_daily.REVENUE';

	/** the column name for the REVENUE_POINTS field */
	const REVENUE_POINTS = 'stat_money_daily.REVENUE_POINTS';

	/** the column name for the PAY_COUNT field */
	const PAY_COUNT = 'stat_money_daily.PAY_COUNT';

	/** the column name for the AVG_CHECK field */
	const AVG_CHECK = 'stat_money_daily.AVG_CHECK';

	/** the column name for the AVG_CHECK_POINTS field */
	const AVG_CHECK_POINTS = 'stat_money_daily.AVG_CHECK_POINTS';

	/** the column name for the INCOMING_FUNDS field */
	const INCOMING_FUNDS = 'stat_money_daily.INCOMING_FUNDS';

	/** the column name for the INCOMING_FUNDS_POINTS field */
	const INCOMING_FUNDS_POINTS = 'stat_money_daily.INCOMING_FUNDS_POINTS';

	/** the column name for the OUTGOING_FUNDS field */
	const OUTGOING_FUNDS = 'stat_money_daily.OUTGOING_FUNDS';

	/** the column name for the OUTGOING_FUNDS_POINTS field */
	const OUTGOING_FUNDS_POINTS = 'stat_money_daily.OUTGOING_FUNDS_POINTS';

	/** the column name for the DIFF_FUNDS field */
	const DIFF_FUNDS = 'stat_money_daily.DIFF_FUNDS';

	/** the column name for the DIFF_FUNDS_POINTS field */
	const DIFF_FUNDS_POINTS = 'stat_money_daily.DIFF_FUNDS_POINTS';

	/** the column name for the AVG_AGENT_REVENUE field */
	const AVG_AGENT_REVENUE = 'stat_money_daily.AVG_AGENT_REVENUE';

	/** the column name for the AVG_AGENT_REVENUE_POINTS field */
	const AVG_AGENT_REVENUE_POINTS = 'stat_money_daily.AVG_AGENT_REVENUE_POINTS';

	/** the column name for the AVG_ADVERT_COST field */
	const AVG_ADVERT_COST = 'stat_money_daily.AVG_ADVERT_COST';

	/** the column name for the AVG_ADVERT_COST_POINTS field */
	const AVG_ADVERT_COST_POINTS = 'stat_money_daily.AVG_ADVERT_COST_POINTS';

	/** the column name for the AVG_ACTIVE_AGENT_REVERNUE field */
	const AVG_ACTIVE_AGENT_REVERNUE = 'stat_money_daily.AVG_ACTIVE_AGENT_REVERNUE';

	/** the column name for the AVG_ACTIVE_AGENT_REVENUE_POINTS field */
	const AVG_ACTIVE_AGENT_REVENUE_POINTS = 'stat_money_daily.AVG_ACTIVE_AGENT_REVENUE_POINTS';

	/** the column name for the AVG_ACTIVE_ADVERT_COST field */
	const AVG_ACTIVE_ADVERT_COST = 'stat_money_daily.AVG_ACTIVE_ADVERT_COST';

	/** the column name for the AVG_ACTIVE_ADVERT_COST_POINTS field */
	const AVG_ACTIVE_ADVERT_COST_POINTS = 'stat_money_daily.AVG_ACTIVE_ADVERT_COST_POINTS';

	/** the column name for the AVG_CLICK_COST field */
	const AVG_CLICK_COST = 'stat_money_daily.AVG_CLICK_COST';

	/** the column name for the AVG_CLICK_COST_POINTS field */
	const AVG_CLICK_COST_POINTS = 'stat_money_daily.AVG_CLICK_COST_POINTS';

	/** the column name for the AVG_CLICK_REVENUE field */
	const AVG_CLICK_REVENUE = 'stat_money_daily.AVG_CLICK_REVENUE';

	/** the column name for the AVG_CLICK_REVENUE_POINTS field */
	const AVG_CLICK_REVENUE_POINTS = 'stat_money_daily.AVG_CLICK_REVENUE_POINTS';

	/** the column name for the ARPU field */
	const ARPU = 'stat_money_daily.ARPU';

	/** the column name for the ARPU_POINTS field */
	const ARPU_POINTS = 'stat_money_daily.ARPU_POINTS';

	/**
	 * An identiy map to hold any loaded instances of StatMoneyDaily objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array StatMoneyDaily[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Date', 'Turnover', 'TurnoverPoints', 'Revenue', 'RevenuePoints', 'PayCount', 'AvgCheck', 'AvgCheckPoints', 'IncomingFunds', 'IncomingFundsPoints', 'OutgoingFunds', 'OutgoingFundsPoints', 'DiffFunds', 'DiffFundsPoints', 'AvgAgentRevenue', 'AvgAgentRevenuePoints', 'AvgAdvertCost', 'AvgAdvertCostPoints', 'AvgActiveAgentRevernue', 'AvgActiveAgentRevenuePoints', 'AvgActiveAdvertCost', 'AvgActiveAdvertCostPoints', 'AvgClickCost', 'AvgClickCostPoints', 'AvgClickRevenue', 'AvgClickRevenuePoints', 'Arpu', 'ArpuPoints', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'date', 'turnover', 'turnoverPoints', 'revenue', 'revenuePoints', 'payCount', 'avgCheck', 'avgCheckPoints', 'incomingFunds', 'incomingFundsPoints', 'outgoingFunds', 'outgoingFundsPoints', 'diffFunds', 'diffFundsPoints', 'avgAgentRevenue', 'avgAgentRevenuePoints', 'avgAdvertCost', 'avgAdvertCostPoints', 'avgActiveAgentRevernue', 'avgActiveAgentRevenuePoints', 'avgActiveAdvertCost', 'avgActiveAdvertCostPoints', 'avgClickCost', 'avgClickCostPoints', 'avgClickRevenue', 'avgClickRevenuePoints', 'arpu', 'arpuPoints', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::DATE, self::TURNOVER, self::TURNOVER_POINTS, self::REVENUE, self::REVENUE_POINTS, self::PAY_COUNT, self::AVG_CHECK, self::AVG_CHECK_POINTS, self::INCOMING_FUNDS, self::INCOMING_FUNDS_POINTS, self::OUTGOING_FUNDS, self::OUTGOING_FUNDS_POINTS, self::DIFF_FUNDS, self::DIFF_FUNDS_POINTS, self::AVG_AGENT_REVENUE, self::AVG_AGENT_REVENUE_POINTS, self::AVG_ADVERT_COST, self::AVG_ADVERT_COST_POINTS, self::AVG_ACTIVE_AGENT_REVERNUE, self::AVG_ACTIVE_AGENT_REVENUE_POINTS, self::AVG_ACTIVE_ADVERT_COST, self::AVG_ACTIVE_ADVERT_COST_POINTS, self::AVG_CLICK_COST, self::AVG_CLICK_COST_POINTS, self::AVG_CLICK_REVENUE, self::AVG_CLICK_REVENUE_POINTS, self::ARPU, self::ARPU_POINTS, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'date', 'turnover', 'turnover_points', 'revenue', 'revenue_points', 'pay_count', 'avg_check', 'avg_check_points', 'incoming_funds', 'incoming_funds_points', 'outgoing_funds', 'outgoing_funds_points', 'diff_funds', 'diff_funds_points', 'avg_agent_revenue', 'avg_agent_revenue_points', 'avg_advert_cost', 'avg_advert_cost_points', 'avg_active_agent_revernue', 'avg_active_agent_revenue_points', 'avg_active_advert_cost', 'avg_active_advert_cost_points', 'avg_click_cost', 'avg_click_cost_points', 'avg_click_revenue', 'avg_click_revenue_points', 'arpu', 'arpu_points', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Date' => 1, 'Turnover' => 2, 'TurnoverPoints' => 3, 'Revenue' => 4, 'RevenuePoints' => 5, 'PayCount' => 6, 'AvgCheck' => 7, 'AvgCheckPoints' => 8, 'IncomingFunds' => 9, 'IncomingFundsPoints' => 10, 'OutgoingFunds' => 11, 'OutgoingFundsPoints' => 12, 'DiffFunds' => 13, 'DiffFundsPoints' => 14, 'AvgAgentRevenue' => 15, 'AvgAgentRevenuePoints' => 16, 'AvgAdvertCost' => 17, 'AvgAdvertCostPoints' => 18, 'AvgActiveAgentRevernue' => 19, 'AvgActiveAgentRevenuePoints' => 20, 'AvgActiveAdvertCost' => 21, 'AvgActiveAdvertCostPoints' => 22, 'AvgClickCost' => 23, 'AvgClickCostPoints' => 24, 'AvgClickRevenue' => 25, 'AvgClickRevenuePoints' => 26, 'Arpu' => 27, 'ArpuPoints' => 28, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'date' => 1, 'turnover' => 2, 'turnoverPoints' => 3, 'revenue' => 4, 'revenuePoints' => 5, 'payCount' => 6, 'avgCheck' => 7, 'avgCheckPoints' => 8, 'incomingFunds' => 9, 'incomingFundsPoints' => 10, 'outgoingFunds' => 11, 'outgoingFundsPoints' => 12, 'diffFunds' => 13, 'diffFundsPoints' => 14, 'avgAgentRevenue' => 15, 'avgAgentRevenuePoints' => 16, 'avgAdvertCost' => 17, 'avgAdvertCostPoints' => 18, 'avgActiveAgentRevernue' => 19, 'avgActiveAgentRevenuePoints' => 20, 'avgActiveAdvertCost' => 21, 'avgActiveAdvertCostPoints' => 22, 'avgClickCost' => 23, 'avgClickCostPoints' => 24, 'avgClickRevenue' => 25, 'avgClickRevenuePoints' => 26, 'arpu' => 27, 'arpuPoints' => 28, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::DATE => 1, self::TURNOVER => 2, self::TURNOVER_POINTS => 3, self::REVENUE => 4, self::REVENUE_POINTS => 5, self::PAY_COUNT => 6, self::AVG_CHECK => 7, self::AVG_CHECK_POINTS => 8, self::INCOMING_FUNDS => 9, self::INCOMING_FUNDS_POINTS => 10, self::OUTGOING_FUNDS => 11, self::OUTGOING_FUNDS_POINTS => 12, self::DIFF_FUNDS => 13, self::DIFF_FUNDS_POINTS => 14, self::AVG_AGENT_REVENUE => 15, self::AVG_AGENT_REVENUE_POINTS => 16, self::AVG_ADVERT_COST => 17, self::AVG_ADVERT_COST_POINTS => 18, self::AVG_ACTIVE_AGENT_REVERNUE => 19, self::AVG_ACTIVE_AGENT_REVENUE_POINTS => 20, self::AVG_ACTIVE_ADVERT_COST => 21, self::AVG_ACTIVE_ADVERT_COST_POINTS => 22, self::AVG_CLICK_COST => 23, self::AVG_CLICK_COST_POINTS => 24, self::AVG_CLICK_REVENUE => 25, self::AVG_CLICK_REVENUE_POINTS => 26, self::ARPU => 27, self::ARPU_POINTS => 28, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'date' => 1, 'turnover' => 2, 'turnover_points' => 3, 'revenue' => 4, 'revenue_points' => 5, 'pay_count' => 6, 'avg_check' => 7, 'avg_check_points' => 8, 'incoming_funds' => 9, 'incoming_funds_points' => 10, 'outgoing_funds' => 11, 'outgoing_funds_points' => 12, 'diff_funds' => 13, 'diff_funds_points' => 14, 'avg_agent_revenue' => 15, 'avg_agent_revenue_points' => 16, 'avg_advert_cost' => 17, 'avg_advert_cost_points' => 18, 'avg_active_agent_revernue' => 19, 'avg_active_agent_revenue_points' => 20, 'avg_active_advert_cost' => 21, 'avg_active_advert_cost_points' => 22, 'avg_click_cost' => 23, 'avg_click_cost_points' => 24, 'avg_click_revenue' => 25, 'avg_click_revenue_points' => 26, 'arpu' => 27, 'arpu_points' => 28, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. StatMoneyDailyPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(StatMoneyDailyPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(StatMoneyDailyPeer::ID);
		$criteria->addSelectColumn(StatMoneyDailyPeer::DATE);
		$criteria->addSelectColumn(StatMoneyDailyPeer::TURNOVER);
		$criteria->addSelectColumn(StatMoneyDailyPeer::TURNOVER_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::REVENUE);
		$criteria->addSelectColumn(StatMoneyDailyPeer::REVENUE_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::PAY_COUNT);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_CHECK);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_CHECK_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::INCOMING_FUNDS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::INCOMING_FUNDS_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::OUTGOING_FUNDS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::OUTGOING_FUNDS_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::DIFF_FUNDS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::DIFF_FUNDS_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_AGENT_REVENUE);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_AGENT_REVENUE_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_ADVERT_COST);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_ADVERT_COST_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_ACTIVE_AGENT_REVERNUE);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_ACTIVE_AGENT_REVENUE_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_ACTIVE_ADVERT_COST);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_ACTIVE_ADVERT_COST_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_CLICK_COST);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_CLICK_COST_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_CLICK_REVENUE);
		$criteria->addSelectColumn(StatMoneyDailyPeer::AVG_CLICK_REVENUE_POINTS);
		$criteria->addSelectColumn(StatMoneyDailyPeer::ARPU);
		$criteria->addSelectColumn(StatMoneyDailyPeer::ARPU_POINTS);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(StatMoneyDailyPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StatMoneyDailyPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(StatMoneyDailyPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseStatMoneyDailyPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     StatMoneyDaily
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = StatMoneyDailyPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return StatMoneyDailyPeer::populateObjects(StatMoneyDailyPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(StatMoneyDailyPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			StatMoneyDailyPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseStatMoneyDailyPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      StatMoneyDaily $value A StatMoneyDaily object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(StatMoneyDaily $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A StatMoneyDaily object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof StatMoneyDaily) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or StatMoneyDaily object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     StatMoneyDaily Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to stat_money_daily
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = StatMoneyDailyPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = StatMoneyDailyPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = StatMoneyDailyPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				StatMoneyDailyPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseStatMoneyDailyPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseStatMoneyDailyPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new StatMoneyDailyTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? StatMoneyDailyPeer::CLASS_DEFAULT : StatMoneyDailyPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a StatMoneyDaily or Criteria object.
	 *
	 * @param      mixed $values Criteria or StatMoneyDaily object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseStatMoneyDailyPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseStatMoneyDailyPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(StatMoneyDailyPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from StatMoneyDaily object
		}

		if ($criteria->containsKey(StatMoneyDailyPeer::ID) && $criteria->keyContainsValue(StatMoneyDailyPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.StatMoneyDailyPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseStatMoneyDailyPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseStatMoneyDailyPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a StatMoneyDaily or Criteria object.
	 *
	 * @param      mixed $values Criteria or StatMoneyDaily object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseStatMoneyDailyPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseStatMoneyDailyPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(StatMoneyDailyPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(StatMoneyDailyPeer::ID);
			$selectCriteria->add(StatMoneyDailyPeer::ID, $criteria->remove(StatMoneyDailyPeer::ID), $comparison);

		} else { // $values is StatMoneyDaily object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseStatMoneyDailyPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseStatMoneyDailyPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the stat_money_daily table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(StatMoneyDailyPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(StatMoneyDailyPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			StatMoneyDailyPeer::clearInstancePool();
			StatMoneyDailyPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a StatMoneyDaily or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or StatMoneyDaily object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(StatMoneyDailyPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			StatMoneyDailyPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof StatMoneyDaily) { // it's a model object
			// invalidate the cache for this single object
			StatMoneyDailyPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(StatMoneyDailyPeer::ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				StatMoneyDailyPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			StatMoneyDailyPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given StatMoneyDaily object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      StatMoneyDaily $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(StatMoneyDaily $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(StatMoneyDailyPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(StatMoneyDailyPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(StatMoneyDailyPeer::DATABASE_NAME, StatMoneyDailyPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     StatMoneyDaily
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = StatMoneyDailyPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(StatMoneyDailyPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(StatMoneyDailyPeer::DATABASE_NAME);
		$criteria->add(StatMoneyDailyPeer::ID, $pk);

		$v = StatMoneyDailyPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(StatMoneyDailyPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(StatMoneyDailyPeer::DATABASE_NAME);
			$criteria->add(StatMoneyDailyPeer::ID, $pks, Criteria::IN);
			$objs = StatMoneyDailyPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array(array('date'));
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseStatMoneyDailyPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseStatMoneyDailyPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseStatMoneyDailyPeer::buildTableMap();

