<?php

/**
 * Base class that represents a row from the 'fast_click' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:13 2011
 *
 * @package    lib.model.om
 */
abstract class BaseFastClick extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FastClickPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the time field.
	 * @var        int
	 */
	protected $time;

	/**
	 * The value for the ua_id field.
	 * @var        int
	 */
	protected $ua_id;

	/**
	 * The value for the a_hash field.
	 * @var        string
	 */
	protected $a_hash;

	/**
	 * The value for the ad_id field.
	 * @var        int
	 */
	protected $ad_id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the advert_id field.
	 * @var        int
	 */
	protected $advert_id;

	/**
	 * The value for the ip field.
	 * @var        int
	 */
	protected $ip;

	/**
	 * The value for the subnet field.
	 * @var        int
	 */
	protected $subnet;

	/**
	 * The value for the ref field.
	 * @var        string
	 */
	protected $ref;

	/**
	 * The value for the last_click_time field.
	 * @var        int
	 */
	protected $last_click_time;

	/**
	 * The value for the no_cookie field.
	 * @var        int
	 */
	protected $no_cookie;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'FastClickPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [time] column value.
	 * 
	 * @return     int
	 */
	public function getTime()
	{
		return $this->time;
	}

	/**
	 * Get the [ua_id] column value.
	 * 
	 * @return     int
	 */
	public function getUaId()
	{
		return $this->ua_id;
	}

	/**
	 * Get the [a_hash] column value.
	 * 
	 * @return     string
	 */
	public function getAHash()
	{
		return $this->a_hash;
	}

	/**
	 * Get the [ad_id] column value.
	 * 
	 * @return     int
	 */
	public function getAdId()
	{
		return $this->ad_id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [advert_id] column value.
	 * 
	 * @return     int
	 */
	public function getAdvertId()
	{
		return $this->advert_id;
	}

	/**
	 * Get the [ip] column value.
	 * 
	 * @return     int
	 */
	public function getIp()
	{
		return $this->ip;
	}

	/**
	 * Get the [subnet] column value.
	 * 
	 * @return     int
	 */
	public function getSubnet()
	{
		return $this->subnet;
	}

	/**
	 * Get the [ref] column value.
	 * 
	 * @return     string
	 */
	public function getRef()
	{
		return $this->ref;
	}

	/**
	 * Get the [last_click_time] column value.
	 * 
	 * @return     int
	 */
	public function getLastClickTime()
	{
		return $this->last_click_time;
	}

	/**
	 * Get the [no_cookie] column value.
	 * 
	 * @return     int
	 */
	public function getNoCookie()
	{
		return $this->no_cookie;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = FastClickPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [time] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setTime($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->time !== $v) {
			$this->time = $v;
			$this->modifiedColumns[] = FastClickPeer::TIME;
		}

		return $this;
	} // setTime()

	/**
	 * Set the value of [ua_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setUaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->ua_id !== $v) {
			$this->ua_id = $v;
			$this->modifiedColumns[] = FastClickPeer::UA_ID;
		}

		return $this;
	} // setUaId()

	/**
	 * Set the value of [a_hash] column.
	 * 
	 * @param      string $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setAHash($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->a_hash !== $v) {
			$this->a_hash = $v;
			$this->modifiedColumns[] = FastClickPeer::A_HASH;
		}

		return $this;
	} // setAHash()

	/**
	 * Set the value of [ad_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setAdId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->ad_id !== $v) {
			$this->ad_id = $v;
			$this->modifiedColumns[] = FastClickPeer::AD_ID;
		}

		return $this;
	} // setAdId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = FastClickPeer::USER_ID;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [advert_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setAdvertId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->advert_id !== $v) {
			$this->advert_id = $v;
			$this->modifiedColumns[] = FastClickPeer::ADVERT_ID;
		}

		return $this;
	} // setAdvertId()

	/**
	 * Set the value of [ip] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setIp($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->ip !== $v) {
			$this->ip = $v;
			$this->modifiedColumns[] = FastClickPeer::IP;
		}

		return $this;
	} // setIp()

	/**
	 * Set the value of [subnet] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setSubnet($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->subnet !== $v) {
			$this->subnet = $v;
			$this->modifiedColumns[] = FastClickPeer::SUBNET;
		}

		return $this;
	} // setSubnet()

	/**
	 * Set the value of [ref] column.
	 * 
	 * @param      string $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setRef($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ref !== $v) {
			$this->ref = $v;
			$this->modifiedColumns[] = FastClickPeer::REF;
		}

		return $this;
	} // setRef()

	/**
	 * Set the value of [last_click_time] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setLastClickTime($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->last_click_time !== $v) {
			$this->last_click_time = $v;
			$this->modifiedColumns[] = FastClickPeer::LAST_CLICK_TIME;
		}

		return $this;
	} // setLastClickTime()

	/**
	 * Set the value of [no_cookie] column.
	 * 
	 * @param      int $v new value
	 * @return     FastClick The current object (for fluent API support)
	 */
	public function setNoCookie($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->no_cookie !== $v) {
			$this->no_cookie = $v;
			$this->modifiedColumns[] = FastClickPeer::NO_COOKIE;
		}

		return $this;
	} // setNoCookie()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->time = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->ua_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->a_hash = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->ad_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->user_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->advert_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->ip = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->subnet = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->ref = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->last_click_time = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->no_cookie = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = FastClickPeer::NUM_COLUMNS - FastClickPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating FastClick object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FastClickPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FastClickPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FastClickPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFastClick:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				FastClickPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFastClick:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FastClickPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFastClick:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFastClick:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				FastClickPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FastClickPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FastClickPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FastClickPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = FastClickPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FastClickPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getTime();
				break;
			case 2:
				return $this->getUaId();
				break;
			case 3:
				return $this->getAHash();
				break;
			case 4:
				return $this->getAdId();
				break;
			case 5:
				return $this->getUserId();
				break;
			case 6:
				return $this->getAdvertId();
				break;
			case 7:
				return $this->getIp();
				break;
			case 8:
				return $this->getSubnet();
				break;
			case 9:
				return $this->getRef();
				break;
			case 10:
				return $this->getLastClickTime();
				break;
			case 11:
				return $this->getNoCookie();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FastClickPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getTime(),
			$keys[2] => $this->getUaId(),
			$keys[3] => $this->getAHash(),
			$keys[4] => $this->getAdId(),
			$keys[5] => $this->getUserId(),
			$keys[6] => $this->getAdvertId(),
			$keys[7] => $this->getIp(),
			$keys[8] => $this->getSubnet(),
			$keys[9] => $this->getRef(),
			$keys[10] => $this->getLastClickTime(),
			$keys[11] => $this->getNoCookie(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FastClickPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setTime($value);
				break;
			case 2:
				$this->setUaId($value);
				break;
			case 3:
				$this->setAHash($value);
				break;
			case 4:
				$this->setAdId($value);
				break;
			case 5:
				$this->setUserId($value);
				break;
			case 6:
				$this->setAdvertId($value);
				break;
			case 7:
				$this->setIp($value);
				break;
			case 8:
				$this->setSubnet($value);
				break;
			case 9:
				$this->setRef($value);
				break;
			case 10:
				$this->setLastClickTime($value);
				break;
			case 11:
				$this->setNoCookie($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FastClickPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTime($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUaId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setAHash($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAdId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setUserId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setAdvertId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setIp($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setSubnet($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setRef($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setLastClickTime($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setNoCookie($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FastClickPeer::DATABASE_NAME);

		if ($this->isColumnModified(FastClickPeer::ID)) $criteria->add(FastClickPeer::ID, $this->id);
		if ($this->isColumnModified(FastClickPeer::TIME)) $criteria->add(FastClickPeer::TIME, $this->time);
		if ($this->isColumnModified(FastClickPeer::UA_ID)) $criteria->add(FastClickPeer::UA_ID, $this->ua_id);
		if ($this->isColumnModified(FastClickPeer::A_HASH)) $criteria->add(FastClickPeer::A_HASH, $this->a_hash);
		if ($this->isColumnModified(FastClickPeer::AD_ID)) $criteria->add(FastClickPeer::AD_ID, $this->ad_id);
		if ($this->isColumnModified(FastClickPeer::USER_ID)) $criteria->add(FastClickPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(FastClickPeer::ADVERT_ID)) $criteria->add(FastClickPeer::ADVERT_ID, $this->advert_id);
		if ($this->isColumnModified(FastClickPeer::IP)) $criteria->add(FastClickPeer::IP, $this->ip);
		if ($this->isColumnModified(FastClickPeer::SUBNET)) $criteria->add(FastClickPeer::SUBNET, $this->subnet);
		if ($this->isColumnModified(FastClickPeer::REF)) $criteria->add(FastClickPeer::REF, $this->ref);
		if ($this->isColumnModified(FastClickPeer::LAST_CLICK_TIME)) $criteria->add(FastClickPeer::LAST_CLICK_TIME, $this->last_click_time);
		if ($this->isColumnModified(FastClickPeer::NO_COOKIE)) $criteria->add(FastClickPeer::NO_COOKIE, $this->no_cookie);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FastClickPeer::DATABASE_NAME);

		$criteria->add(FastClickPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of FastClick (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTime($this->time);

		$copyObj->setUaId($this->ua_id);

		$copyObj->setAHash($this->a_hash);

		$copyObj->setAdId($this->ad_id);

		$copyObj->setUserId($this->user_id);

		$copyObj->setAdvertId($this->advert_id);

		$copyObj->setIp($this->ip);

		$copyObj->setSubnet($this->subnet);

		$copyObj->setRef($this->ref);

		$copyObj->setLastClickTime($this->last_click_time);

		$copyObj->setNoCookie($this->no_cookie);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     FastClick Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FastClickPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FastClickPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseFastClick:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseFastClick::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseFastClick
