<?php

/**
 * Base class that represents a row from the 'advertise' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:12 2011
 *
 * @package    lib.model.om
 */
abstract class BaseAdvertise extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AdvertisePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the type field.
	 * @var        int
	 */
	protected $type;

	/**
	 * The value for the owner_id field.
	 * @var        int
	 */
	protected $owner_id;

	/**
	 * The value for the category_id field.
	 * @var        int
	 */
	protected $category_id;

	/**
	 * The value for the status field.
	 * @var        int
	 */
	protected $status;

	/**
	 * The value for the subject field.
	 * @var        string
	 */
	protected $subject;

	/**
	 * The value for the text field.
	 * @var        string
	 */
	protected $text;

	/**
	 * The value for the image field.
	 * @var        string
	 */
	protected $image;

	/**
	 * The value for the html field.
	 * @var        string
	 */
	protected $html;

	/**
	 * The value for the url field.
	 * @var        string
	 */
	protected $url;

	/**
	 * The value for the cost field.
	 * @var        int
	 */
	protected $cost;

	/**
	 * The value for the agents field.
	 * @var        int
	 */
	protected $agents;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        User
	 */
	protected $aUser;

	/**
	 * @var        AdvertiseCatalog
	 */
	protected $aAdvertiseCatalog;

	/**
	 * @var        array StatAdvertDaily[] Collection to store aggregation of StatAdvertDaily objects.
	 */
	protected $collStatAdvertDailys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collStatAdvertDailys.
	 */
	private $lastStatAdvertDailyCriteria = null;

	/**
	 * @var        array UserAdvertise[] Collection to store aggregation of UserAdvertise objects.
	 */
	protected $collUserAdvertises;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserAdvertises.
	 */
	private $lastUserAdvertiseCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AdvertisePeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [type] column value.
	 * 
	 * @return     int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Get the [owner_id] column value.
	 * 
	 * @return     int
	 */
	public function getOwnerId()
	{
		return $this->owner_id;
	}

	/**
	 * Get the [category_id] column value.
	 * 
	 * @return     int
	 */
	public function getCategoryId()
	{
		return $this->category_id;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     int
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [subject] column value.
	 * 
	 * @return     string
	 */
	public function getSubject()
	{
		return $this->subject;
	}

	/**
	 * Get the [text] column value.
	 * 
	 * @return     string
	 */
	public function getText()
	{
		return $this->text;
	}

	/**
	 * Get the [image] column value.
	 * 
	 * @return     string
	 */
	public function getImage()
	{
		return $this->image;
	}

	/**
	 * Get the [html] column value.
	 * 
	 * @return     string
	 */
	public function getHtml()
	{
		return $this->html;
	}

	/**
	 * Get the [url] column value.
	 * 
	 * @return     string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Get the [cost] column value.
	 * 
	 * @return     int
	 */
	public function getCost()
	{
		return $this->cost;
	}

	/**
	 * Get the [agents] column value.
	 * 
	 * @return     int
	 */
	public function getAgents()
	{
		return $this->agents;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AdvertisePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [type] column.
	 * 
	 * @param      int $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setType($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->type !== $v) {
			$this->type = $v;
			$this->modifiedColumns[] = AdvertisePeer::TYPE;
		}

		return $this;
	} // setType()

	/**
	 * Set the value of [owner_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setOwnerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->owner_id !== $v) {
			$this->owner_id = $v;
			$this->modifiedColumns[] = AdvertisePeer::OWNER_ID;
		}

		if ($this->aUser !== null && $this->aUser->getId() !== $v) {
			$this->aUser = null;
		}

		return $this;
	} // setOwnerId()

	/**
	 * Set the value of [category_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setCategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->category_id !== $v) {
			$this->category_id = $v;
			$this->modifiedColumns[] = AdvertisePeer::CATEGORY_ID;
		}

		if ($this->aAdvertiseCatalog !== null && $this->aAdvertiseCatalog->getId() !== $v) {
			$this->aAdvertiseCatalog = null;
		}

		return $this;
	} // setCategoryId()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      int $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = AdvertisePeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Set the value of [subject] column.
	 * 
	 * @param      string $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setSubject($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->subject !== $v) {
			$this->subject = $v;
			$this->modifiedColumns[] = AdvertisePeer::SUBJECT;
		}

		return $this;
	} // setSubject()

	/**
	 * Set the value of [text] column.
	 * 
	 * @param      string $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setText($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->text !== $v) {
			$this->text = $v;
			$this->modifiedColumns[] = AdvertisePeer::TEXT;
		}

		return $this;
	} // setText()

	/**
	 * Set the value of [image] column.
	 * 
	 * @param      string $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setImage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->image !== $v) {
			$this->image = $v;
			$this->modifiedColumns[] = AdvertisePeer::IMAGE;
		}

		return $this;
	} // setImage()

	/**
	 * Set the value of [html] column.
	 * 
	 * @param      string $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setHtml($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->html !== $v) {
			$this->html = $v;
			$this->modifiedColumns[] = AdvertisePeer::HTML;
		}

		return $this;
	} // setHtml()

	/**
	 * Set the value of [url] column.
	 * 
	 * @param      string $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setUrl($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->url !== $v) {
			$this->url = $v;
			$this->modifiedColumns[] = AdvertisePeer::URL;
		}

		return $this;
	} // setUrl()

	/**
	 * Set the value of [cost] column.
	 * 
	 * @param      int $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setCost($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cost !== $v) {
			$this->cost = $v;
			$this->modifiedColumns[] = AdvertisePeer::COST;
		}

		return $this;
	} // setCost()

	/**
	 * Set the value of [agents] column.
	 * 
	 * @param      int $v new value
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setAgents($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->agents !== $v) {
			$this->agents = $v;
			$this->modifiedColumns[] = AdvertisePeer::AGENTS;
		}

		return $this;
	} // setAgents()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AdvertisePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Advertise The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AdvertisePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->type = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->owner_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->category_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->status = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->subject = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->text = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->image = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->html = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->url = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->cost = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->agents = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->created_at = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->updated_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 14; // 14 = AdvertisePeer::NUM_COLUMNS - AdvertisePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Advertise object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUser !== null && $this->owner_id !== $this->aUser->getId()) {
			$this->aUser = null;
		}
		if ($this->aAdvertiseCatalog !== null && $this->category_id !== $this->aAdvertiseCatalog->getId()) {
			$this->aAdvertiseCatalog = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AdvertisePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AdvertisePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUser = null;
			$this->aAdvertiseCatalog = null;
			$this->collStatAdvertDailys = null;
			$this->lastStatAdvertDailyCriteria = null;

			$this->collUserAdvertises = null;
			$this->lastUserAdvertiseCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AdvertisePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAdvertise:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				AdvertisePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAdvertise:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AdvertisePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAdvertise:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(AdvertisePeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(AdvertisePeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAdvertise:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				AdvertisePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUser !== null) {
				if ($this->aUser->isModified() || $this->aUser->isNew()) {
					$affectedRows += $this->aUser->save($con);
				}
				$this->setUser($this->aUser);
			}

			if ($this->aAdvertiseCatalog !== null) {
				if ($this->aAdvertiseCatalog->isModified() || $this->aAdvertiseCatalog->isNew()) {
					$affectedRows += $this->aAdvertiseCatalog->save($con);
				}
				$this->setAdvertiseCatalog($this->aAdvertiseCatalog);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AdvertisePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AdvertisePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AdvertisePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collStatAdvertDailys !== null) {
				foreach ($this->collStatAdvertDailys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUserAdvertises !== null) {
				foreach ($this->collUserAdvertises as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUser !== null) {
				if (!$this->aUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUser->getValidationFailures());
				}
			}

			if ($this->aAdvertiseCatalog !== null) {
				if (!$this->aAdvertiseCatalog->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAdvertiseCatalog->getValidationFailures());
				}
			}


			if (($retval = AdvertisePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collStatAdvertDailys !== null) {
					foreach ($this->collStatAdvertDailys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUserAdvertises !== null) {
					foreach ($this->collUserAdvertises as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AdvertisePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getType();
				break;
			case 2:
				return $this->getOwnerId();
				break;
			case 3:
				return $this->getCategoryId();
				break;
			case 4:
				return $this->getStatus();
				break;
			case 5:
				return $this->getSubject();
				break;
			case 6:
				return $this->getText();
				break;
			case 7:
				return $this->getImage();
				break;
			case 8:
				return $this->getHtml();
				break;
			case 9:
				return $this->getUrl();
				break;
			case 10:
				return $this->getCost();
				break;
			case 11:
				return $this->getAgents();
				break;
			case 12:
				return $this->getCreatedAt();
				break;
			case 13:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AdvertisePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getType(),
			$keys[2] => $this->getOwnerId(),
			$keys[3] => $this->getCategoryId(),
			$keys[4] => $this->getStatus(),
			$keys[5] => $this->getSubject(),
			$keys[6] => $this->getText(),
			$keys[7] => $this->getImage(),
			$keys[8] => $this->getHtml(),
			$keys[9] => $this->getUrl(),
			$keys[10] => $this->getCost(),
			$keys[11] => $this->getAgents(),
			$keys[12] => $this->getCreatedAt(),
			$keys[13] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AdvertisePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setType($value);
				break;
			case 2:
				$this->setOwnerId($value);
				break;
			case 3:
				$this->setCategoryId($value);
				break;
			case 4:
				$this->setStatus($value);
				break;
			case 5:
				$this->setSubject($value);
				break;
			case 6:
				$this->setText($value);
				break;
			case 7:
				$this->setImage($value);
				break;
			case 8:
				$this->setHtml($value);
				break;
			case 9:
				$this->setUrl($value);
				break;
			case 10:
				$this->setCost($value);
				break;
			case 11:
				$this->setAgents($value);
				break;
			case 12:
				$this->setCreatedAt($value);
				break;
			case 13:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AdvertisePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setType($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setOwnerId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCategoryId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setStatus($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSubject($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setText($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setImage($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setHtml($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUrl($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setCost($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setAgents($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setCreatedAt($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setUpdatedAt($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AdvertisePeer::DATABASE_NAME);

		if ($this->isColumnModified(AdvertisePeer::ID)) $criteria->add(AdvertisePeer::ID, $this->id);
		if ($this->isColumnModified(AdvertisePeer::TYPE)) $criteria->add(AdvertisePeer::TYPE, $this->type);
		if ($this->isColumnModified(AdvertisePeer::OWNER_ID)) $criteria->add(AdvertisePeer::OWNER_ID, $this->owner_id);
		if ($this->isColumnModified(AdvertisePeer::CATEGORY_ID)) $criteria->add(AdvertisePeer::CATEGORY_ID, $this->category_id);
		if ($this->isColumnModified(AdvertisePeer::STATUS)) $criteria->add(AdvertisePeer::STATUS, $this->status);
		if ($this->isColumnModified(AdvertisePeer::SUBJECT)) $criteria->add(AdvertisePeer::SUBJECT, $this->subject);
		if ($this->isColumnModified(AdvertisePeer::TEXT)) $criteria->add(AdvertisePeer::TEXT, $this->text);
		if ($this->isColumnModified(AdvertisePeer::IMAGE)) $criteria->add(AdvertisePeer::IMAGE, $this->image);
		if ($this->isColumnModified(AdvertisePeer::HTML)) $criteria->add(AdvertisePeer::HTML, $this->html);
		if ($this->isColumnModified(AdvertisePeer::URL)) $criteria->add(AdvertisePeer::URL, $this->url);
		if ($this->isColumnModified(AdvertisePeer::COST)) $criteria->add(AdvertisePeer::COST, $this->cost);
		if ($this->isColumnModified(AdvertisePeer::AGENTS)) $criteria->add(AdvertisePeer::AGENTS, $this->agents);
		if ($this->isColumnModified(AdvertisePeer::CREATED_AT)) $criteria->add(AdvertisePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(AdvertisePeer::UPDATED_AT)) $criteria->add(AdvertisePeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AdvertisePeer::DATABASE_NAME);

		$criteria->add(AdvertisePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Advertise (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setType($this->type);

		$copyObj->setOwnerId($this->owner_id);

		$copyObj->setCategoryId($this->category_id);

		$copyObj->setStatus($this->status);

		$copyObj->setSubject($this->subject);

		$copyObj->setText($this->text);

		$copyObj->setImage($this->image);

		$copyObj->setHtml($this->html);

		$copyObj->setUrl($this->url);

		$copyObj->setCost($this->cost);

		$copyObj->setAgents($this->agents);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getStatAdvertDailys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addStatAdvertDaily($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUserAdvertises() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserAdvertise($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Advertise Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AdvertisePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AdvertisePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a User object.
	 *
	 * @param      User $v
	 * @return     Advertise The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUser(User $v = null)
	{
		if ($v === null) {
			$this->setOwnerId(NULL);
		} else {
			$this->setOwnerId($v->getId());
		}

		$this->aUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the User object, it will not be re-added.
		if ($v !== null) {
			$v->addAdvertise($this);
		}

		return $this;
	}


	/**
	 * Get the associated User object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     User The associated User object.
	 * @throws     PropelException
	 */
	public function getUser(PropelPDO $con = null)
	{
		if ($this->aUser === null && ($this->owner_id !== null)) {
			$this->aUser = UserPeer::retrieveByPk($this->owner_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUser->addAdvertises($this);
			 */
		}
		return $this->aUser;
	}

	/**
	 * Declares an association between this object and a AdvertiseCatalog object.
	 *
	 * @param      AdvertiseCatalog $v
	 * @return     Advertise The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAdvertiseCatalog(AdvertiseCatalog $v = null)
	{
		if ($v === null) {
			$this->setCategoryId(NULL);
		} else {
			$this->setCategoryId($v->getId());
		}

		$this->aAdvertiseCatalog = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the AdvertiseCatalog object, it will not be re-added.
		if ($v !== null) {
			$v->addAdvertise($this);
		}

		return $this;
	}


	/**
	 * Get the associated AdvertiseCatalog object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     AdvertiseCatalog The associated AdvertiseCatalog object.
	 * @throws     PropelException
	 */
	public function getAdvertiseCatalog(PropelPDO $con = null)
	{
		if ($this->aAdvertiseCatalog === null && ($this->category_id !== null)) {
			$this->aAdvertiseCatalog = AdvertiseCatalogPeer::retrieveByPk($this->category_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAdvertiseCatalog->addAdvertises($this);
			 */
		}
		return $this->aAdvertiseCatalog;
	}

	/**
	 * Clears out the collStatAdvertDailys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addStatAdvertDailys()
	 */
	public function clearStatAdvertDailys()
	{
		$this->collStatAdvertDailys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collStatAdvertDailys collection (array).
	 *
	 * By default this just sets the collStatAdvertDailys collection to an empty array (like clearcollStatAdvertDailys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initStatAdvertDailys()
	{
		$this->collStatAdvertDailys = array();
	}

	/**
	 * Gets an array of StatAdvertDaily objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Advertise has previously been saved, it will retrieve
	 * related StatAdvertDailys from storage. If this Advertise is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array StatAdvertDaily[]
	 * @throws     PropelException
	 */
	public function getStatAdvertDailys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvertisePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collStatAdvertDailys === null) {
			if ($this->isNew()) {
			   $this->collStatAdvertDailys = array();
			} else {

				$criteria->add(StatAdvertDailyPeer::AD_ID, $this->id);

				StatAdvertDailyPeer::addSelectColumns($criteria);
				$this->collStatAdvertDailys = StatAdvertDailyPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(StatAdvertDailyPeer::AD_ID, $this->id);

				StatAdvertDailyPeer::addSelectColumns($criteria);
				if (!isset($this->lastStatAdvertDailyCriteria) || !$this->lastStatAdvertDailyCriteria->equals($criteria)) {
					$this->collStatAdvertDailys = StatAdvertDailyPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastStatAdvertDailyCriteria = $criteria;
		return $this->collStatAdvertDailys;
	}

	/**
	 * Returns the number of related StatAdvertDaily objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related StatAdvertDaily objects.
	 * @throws     PropelException
	 */
	public function countStatAdvertDailys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvertisePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collStatAdvertDailys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(StatAdvertDailyPeer::AD_ID, $this->id);

				$count = StatAdvertDailyPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(StatAdvertDailyPeer::AD_ID, $this->id);

				if (!isset($this->lastStatAdvertDailyCriteria) || !$this->lastStatAdvertDailyCriteria->equals($criteria)) {
					$count = StatAdvertDailyPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collStatAdvertDailys);
				}
			} else {
				$count = count($this->collStatAdvertDailys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a StatAdvertDaily object to this object
	 * through the StatAdvertDaily foreign key attribute.
	 *
	 * @param      StatAdvertDaily $l StatAdvertDaily
	 * @return     void
	 * @throws     PropelException
	 */
	public function addStatAdvertDaily(StatAdvertDaily $l)
	{
		if ($this->collStatAdvertDailys === null) {
			$this->initStatAdvertDailys();
		}
		if (!in_array($l, $this->collStatAdvertDailys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collStatAdvertDailys, $l);
			$l->setAdvertise($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Advertise is new, it will return
	 * an empty collection; or if this Advertise has previously
	 * been saved, it will retrieve related StatAdvertDailys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Advertise.
	 */
	public function getStatAdvertDailysJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvertisePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collStatAdvertDailys === null) {
			if ($this->isNew()) {
				$this->collStatAdvertDailys = array();
			} else {

				$criteria->add(StatAdvertDailyPeer::AD_ID, $this->id);

				$this->collStatAdvertDailys = StatAdvertDailyPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(StatAdvertDailyPeer::AD_ID, $this->id);

			if (!isset($this->lastStatAdvertDailyCriteria) || !$this->lastStatAdvertDailyCriteria->equals($criteria)) {
				$this->collStatAdvertDailys = StatAdvertDailyPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastStatAdvertDailyCriteria = $criteria;

		return $this->collStatAdvertDailys;
	}

	/**
	 * Clears out the collUserAdvertises collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserAdvertises()
	 */
	public function clearUserAdvertises()
	{
		$this->collUserAdvertises = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserAdvertises collection (array).
	 *
	 * By default this just sets the collUserAdvertises collection to an empty array (like clearcollUserAdvertises());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserAdvertises()
	{
		$this->collUserAdvertises = array();
	}

	/**
	 * Gets an array of UserAdvertise objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Advertise has previously been saved, it will retrieve
	 * related UserAdvertises from storage. If this Advertise is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserAdvertise[]
	 * @throws     PropelException
	 */
	public function getUserAdvertises($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvertisePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserAdvertises === null) {
			if ($this->isNew()) {
			   $this->collUserAdvertises = array();
			} else {

				$criteria->add(UserAdvertisePeer::ADVERTISE_ID, $this->id);

				UserAdvertisePeer::addSelectColumns($criteria);
				$this->collUserAdvertises = UserAdvertisePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserAdvertisePeer::ADVERTISE_ID, $this->id);

				UserAdvertisePeer::addSelectColumns($criteria);
				if (!isset($this->lastUserAdvertiseCriteria) || !$this->lastUserAdvertiseCriteria->equals($criteria)) {
					$this->collUserAdvertises = UserAdvertisePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserAdvertiseCriteria = $criteria;
		return $this->collUserAdvertises;
	}

	/**
	 * Returns the number of related UserAdvertise objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserAdvertise objects.
	 * @throws     PropelException
	 */
	public function countUserAdvertises(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvertisePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserAdvertises === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserAdvertisePeer::ADVERTISE_ID, $this->id);

				$count = UserAdvertisePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserAdvertisePeer::ADVERTISE_ID, $this->id);

				if (!isset($this->lastUserAdvertiseCriteria) || !$this->lastUserAdvertiseCriteria->equals($criteria)) {
					$count = UserAdvertisePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collUserAdvertises);
				}
			} else {
				$count = count($this->collUserAdvertises);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UserAdvertise object to this object
	 * through the UserAdvertise foreign key attribute.
	 *
	 * @param      UserAdvertise $l UserAdvertise
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserAdvertise(UserAdvertise $l)
	{
		if ($this->collUserAdvertises === null) {
			$this->initUserAdvertises();
		}
		if (!in_array($l, $this->collUserAdvertises, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserAdvertises, $l);
			$l->setAdvertise($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Advertise is new, it will return
	 * an empty collection; or if this Advertise has previously
	 * been saved, it will retrieve related UserAdvertises from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Advertise.
	 */
	public function getUserAdvertisesJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AdvertisePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserAdvertises === null) {
			if ($this->isNew()) {
				$this->collUserAdvertises = array();
			} else {

				$criteria->add(UserAdvertisePeer::ADVERTISE_ID, $this->id);

				$this->collUserAdvertises = UserAdvertisePeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserAdvertisePeer::ADVERTISE_ID, $this->id);

			if (!isset($this->lastUserAdvertiseCriteria) || !$this->lastUserAdvertiseCriteria->equals($criteria)) {
				$this->collUserAdvertises = UserAdvertisePeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserAdvertiseCriteria = $criteria;

		return $this->collUserAdvertises;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collStatAdvertDailys) {
				foreach ((array) $this->collStatAdvertDailys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUserAdvertises) {
				foreach ((array) $this->collUserAdvertises as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collStatAdvertDailys = null;
		$this->collUserAdvertises = null;
			$this->aUser = null;
			$this->aAdvertiseCatalog = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAdvertise:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAdvertise::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAdvertise
