<?php

/**
 * Base class that represents a row from the 'user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun  1 18:48:14 2011
 *
 * @package    lib.model.om
 */
abstract class BaseUser extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UserPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the role field.
	 * @var        int
	 */
	protected $role;

	/**
	 * The value for the status field.
	 * @var        int
	 */
	protected $status;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the visit_at field.
	 * @var        string
	 */
	protected $visit_at;

	/**
	 * The value for the ip_register field.
	 * @var        string
	 */
	protected $ip_register;

	/**
	 * The value for the ip_last field.
	 * @var        string
	 */
	protected $ip_last;

	/**
	 * The value for the last_action field.
	 * @var        int
	 */
	protected $last_action;

	/**
	 * @var        array Account[] Collection to store aggregation of Account objects.
	 */
	protected $collAccounts;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAccounts.
	 */
	private $lastAccountCriteria = null;

	/**
	 * @var        array Advertise[] Collection to store aggregation of Advertise objects.
	 */
	protected $collAdvertises;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAdvertises.
	 */
	private $lastAdvertiseCriteria = null;

	/**
	 * @var        array OutgoingFunds[] Collection to store aggregation of OutgoingFunds objects.
	 */
	protected $collOutgoingFundss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collOutgoingFundss.
	 */
	private $lastOutgoingFundsCriteria = null;

	/**
	 * @var        array StatAdvertDaily[] Collection to store aggregation of StatAdvertDaily objects.
	 */
	protected $collStatAdvertDailys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collStatAdvertDailys.
	 */
	private $lastStatAdvertDailyCriteria = null;

	/**
	 * @var        array StatAgentDaily[] Collection to store aggregation of StatAgentDaily objects.
	 */
	protected $collStatAgentDailys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collStatAgentDailys.
	 */
	private $lastStatAgentDailyCriteria = null;

	/**
	 * @var        array UserAdvertise[] Collection to store aggregation of UserAdvertise objects.
	 */
	protected $collUserAdvertises;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserAdvertises.
	 */
	private $lastUserAdvertiseCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'UserPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [role] column value.
	 * 
	 * @return     int
	 */
	public function getRole()
	{
		return $this->role;
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     int
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [visit_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getVisitAt($format = 'Y-m-d H:i:s')
	{
		if ($this->visit_at === null) {
			return null;
		}


		if ($this->visit_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->visit_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->visit_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [ip_register] column value.
	 * 
	 * @return     string
	 */
	public function getIpRegister()
	{
		return $this->ip_register;
	}

	/**
	 * Get the [ip_last] column value.
	 * 
	 * @return     string
	 */
	public function getIpLast()
	{
		return $this->ip_last;
	}

	/**
	 * Get the [last_action] column value.
	 * 
	 * @return     int
	 */
	public function getLastAction()
	{
		return $this->last_action;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = UserPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = UserPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [role] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setRole($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->role !== $v) {
			$this->role = $v;
			$this->modifiedColumns[] = UserPeer::ROLE;
		}

		return $this;
	} // setRole()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->status !== $v) {
			$this->status = $v;
			$this->modifiedColumns[] = UserPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = UserPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = UserPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     User The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UserPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     User The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UserPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Sets the value of [visit_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     User The current object (for fluent API support)
	 */
	public function setVisitAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->visit_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->visit_at !== null && $tmpDt = new DateTime($this->visit_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->visit_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = UserPeer::VISIT_AT;
			}
		} // if either are not null

		return $this;
	} // setVisitAt()

	/**
	 * Set the value of [ip_register] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setIpRegister($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ip_register !== $v) {
			$this->ip_register = $v;
			$this->modifiedColumns[] = UserPeer::IP_REGISTER;
		}

		return $this;
	} // setIpRegister()

	/**
	 * Set the value of [ip_last] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setIpLast($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ip_last !== $v) {
			$this->ip_last = $v;
			$this->modifiedColumns[] = UserPeer::IP_LAST;
		}

		return $this;
	} // setIpLast()

	/**
	 * Set the value of [last_action] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setLastAction($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->last_action !== $v) {
			$this->last_action = $v;
			$this->modifiedColumns[] = UserPeer::LAST_ACTION;
		}

		return $this;
	} // setLastAction()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->role = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->status = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->email = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->password = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->created_at = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->updated_at = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->visit_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->ip_register = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->ip_last = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->last_action = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = UserPeer::NUM_COLUMNS - UserPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating User object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UserPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collAccounts = null;
			$this->lastAccountCriteria = null;

			$this->collAdvertises = null;
			$this->lastAdvertiseCriteria = null;

			$this->collOutgoingFundss = null;
			$this->lastOutgoingFundsCriteria = null;

			$this->collStatAdvertDailys = null;
			$this->lastStatAdvertDailyCriteria = null;

			$this->collStatAgentDailys = null;
			$this->lastStatAgentDailyCriteria = null;

			$this->collUserAdvertises = null;
			$this->lastUserAdvertiseCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseUser:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				UserPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseUser:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseUser:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(UserPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(UserPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseUser:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				UserPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UserPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UserPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UserPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAccounts !== null) {
				foreach ($this->collAccounts as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collAdvertises !== null) {
				foreach ($this->collAdvertises as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collOutgoingFundss !== null) {
				foreach ($this->collOutgoingFundss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collStatAdvertDailys !== null) {
				foreach ($this->collStatAdvertDailys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collStatAgentDailys !== null) {
				foreach ($this->collStatAgentDailys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUserAdvertises !== null) {
				foreach ($this->collUserAdvertises as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = UserPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAccounts !== null) {
					foreach ($this->collAccounts as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collAdvertises !== null) {
					foreach ($this->collAdvertises as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collOutgoingFundss !== null) {
					foreach ($this->collOutgoingFundss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collStatAdvertDailys !== null) {
					foreach ($this->collStatAdvertDailys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collStatAgentDailys !== null) {
					foreach ($this->collStatAgentDailys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUserAdvertises !== null) {
					foreach ($this->collUserAdvertises as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getRole();
				break;
			case 3:
				return $this->getStatus();
				break;
			case 4:
				return $this->getEmail();
				break;
			case 5:
				return $this->getPassword();
				break;
			case 6:
				return $this->getCreatedAt();
				break;
			case 7:
				return $this->getUpdatedAt();
				break;
			case 8:
				return $this->getVisitAt();
				break;
			case 9:
				return $this->getIpRegister();
				break;
			case 10:
				return $this->getIpLast();
				break;
			case 11:
				return $this->getLastAction();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UserPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getRole(),
			$keys[3] => $this->getStatus(),
			$keys[4] => $this->getEmail(),
			$keys[5] => $this->getPassword(),
			$keys[6] => $this->getCreatedAt(),
			$keys[7] => $this->getUpdatedAt(),
			$keys[8] => $this->getVisitAt(),
			$keys[9] => $this->getIpRegister(),
			$keys[10] => $this->getIpLast(),
			$keys[11] => $this->getLastAction(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setRole($value);
				break;
			case 3:
				$this->setStatus($value);
				break;
			case 4:
				$this->setEmail($value);
				break;
			case 5:
				$this->setPassword($value);
				break;
			case 6:
				$this->setCreatedAt($value);
				break;
			case 7:
				$this->setUpdatedAt($value);
				break;
			case 8:
				$this->setVisitAt($value);
				break;
			case 9:
				$this->setIpRegister($value);
				break;
			case 10:
				$this->setIpLast($value);
				break;
			case 11:
				$this->setLastAction($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UserPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setRole($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setStatus($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setEmail($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPassword($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCreatedAt($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setUpdatedAt($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setVisitAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setIpRegister($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setIpLast($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setLastAction($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UserPeer::DATABASE_NAME);

		if ($this->isColumnModified(UserPeer::ID)) $criteria->add(UserPeer::ID, $this->id);
		if ($this->isColumnModified(UserPeer::NAME)) $criteria->add(UserPeer::NAME, $this->name);
		if ($this->isColumnModified(UserPeer::ROLE)) $criteria->add(UserPeer::ROLE, $this->role);
		if ($this->isColumnModified(UserPeer::STATUS)) $criteria->add(UserPeer::STATUS, $this->status);
		if ($this->isColumnModified(UserPeer::EMAIL)) $criteria->add(UserPeer::EMAIL, $this->email);
		if ($this->isColumnModified(UserPeer::PASSWORD)) $criteria->add(UserPeer::PASSWORD, $this->password);
		if ($this->isColumnModified(UserPeer::CREATED_AT)) $criteria->add(UserPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(UserPeer::UPDATED_AT)) $criteria->add(UserPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(UserPeer::VISIT_AT)) $criteria->add(UserPeer::VISIT_AT, $this->visit_at);
		if ($this->isColumnModified(UserPeer::IP_REGISTER)) $criteria->add(UserPeer::IP_REGISTER, $this->ip_register);
		if ($this->isColumnModified(UserPeer::IP_LAST)) $criteria->add(UserPeer::IP_LAST, $this->ip_last);
		if ($this->isColumnModified(UserPeer::LAST_ACTION)) $criteria->add(UserPeer::LAST_ACTION, $this->last_action);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UserPeer::DATABASE_NAME);

		$criteria->add(UserPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of User (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setRole($this->role);

		$copyObj->setStatus($this->status);

		$copyObj->setEmail($this->email);

		$copyObj->setPassword($this->password);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setVisitAt($this->visit_at);

		$copyObj->setIpRegister($this->ip_register);

		$copyObj->setIpLast($this->ip_last);

		$copyObj->setLastAction($this->last_action);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAccounts() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAccount($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getAdvertises() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAdvertise($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getOutgoingFundss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addOutgoingFunds($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getStatAdvertDailys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addStatAdvertDaily($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getStatAgentDailys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addStatAgentDaily($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUserAdvertises() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserAdvertise($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     User Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UserPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UserPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collAccounts collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAccounts()
	 */
	public function clearAccounts()
	{
		$this->collAccounts = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAccounts collection (array).
	 *
	 * By default this just sets the collAccounts collection to an empty array (like clearcollAccounts());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAccounts()
	{
		$this->collAccounts = array();
	}

	/**
	 * Gets an array of Account objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related Accounts from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Account[]
	 * @throws     PropelException
	 */
	public function getAccounts($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAccounts === null) {
			if ($this->isNew()) {
			   $this->collAccounts = array();
			} else {

				$criteria->add(AccountPeer::USER_ID, $this->id);

				AccountPeer::addSelectColumns($criteria);
				$this->collAccounts = AccountPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AccountPeer::USER_ID, $this->id);

				AccountPeer::addSelectColumns($criteria);
				if (!isset($this->lastAccountCriteria) || !$this->lastAccountCriteria->equals($criteria)) {
					$this->collAccounts = AccountPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAccountCriteria = $criteria;
		return $this->collAccounts;
	}

	/**
	 * Returns the number of related Account objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Account objects.
	 * @throws     PropelException
	 */
	public function countAccounts(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAccounts === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AccountPeer::USER_ID, $this->id);

				$count = AccountPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AccountPeer::USER_ID, $this->id);

				if (!isset($this->lastAccountCriteria) || !$this->lastAccountCriteria->equals($criteria)) {
					$count = AccountPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAccounts);
				}
			} else {
				$count = count($this->collAccounts);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Account object to this object
	 * through the Account foreign key attribute.
	 *
	 * @param      Account $l Account
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAccount(Account $l)
	{
		if ($this->collAccounts === null) {
			$this->initAccounts();
		}
		if (!in_array($l, $this->collAccounts, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAccounts, $l);
			$l->setUser($this);
		}
	}

	/**
	 * Clears out the collAdvertises collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAdvertises()
	 */
	public function clearAdvertises()
	{
		$this->collAdvertises = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAdvertises collection (array).
	 *
	 * By default this just sets the collAdvertises collection to an empty array (like clearcollAdvertises());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAdvertises()
	{
		$this->collAdvertises = array();
	}

	/**
	 * Gets an array of Advertise objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related Advertises from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Advertise[]
	 * @throws     PropelException
	 */
	public function getAdvertises($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAdvertises === null) {
			if ($this->isNew()) {
			   $this->collAdvertises = array();
			} else {

				$criteria->add(AdvertisePeer::OWNER_ID, $this->id);

				AdvertisePeer::addSelectColumns($criteria);
				$this->collAdvertises = AdvertisePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AdvertisePeer::OWNER_ID, $this->id);

				AdvertisePeer::addSelectColumns($criteria);
				if (!isset($this->lastAdvertiseCriteria) || !$this->lastAdvertiseCriteria->equals($criteria)) {
					$this->collAdvertises = AdvertisePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAdvertiseCriteria = $criteria;
		return $this->collAdvertises;
	}

	/**
	 * Returns the number of related Advertise objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Advertise objects.
	 * @throws     PropelException
	 */
	public function countAdvertises(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAdvertises === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AdvertisePeer::OWNER_ID, $this->id);

				$count = AdvertisePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AdvertisePeer::OWNER_ID, $this->id);

				if (!isset($this->lastAdvertiseCriteria) || !$this->lastAdvertiseCriteria->equals($criteria)) {
					$count = AdvertisePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAdvertises);
				}
			} else {
				$count = count($this->collAdvertises);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Advertise object to this object
	 * through the Advertise foreign key attribute.
	 *
	 * @param      Advertise $l Advertise
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAdvertise(Advertise $l)
	{
		if ($this->collAdvertises === null) {
			$this->initAdvertises();
		}
		if (!in_array($l, $this->collAdvertises, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAdvertises, $l);
			$l->setUser($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this User is new, it will return
	 * an empty collection; or if this User has previously
	 * been saved, it will retrieve related Advertises from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in User.
	 */
	public function getAdvertisesJoinAdvertiseCatalog($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAdvertises === null) {
			if ($this->isNew()) {
				$this->collAdvertises = array();
			} else {

				$criteria->add(AdvertisePeer::OWNER_ID, $this->id);

				$this->collAdvertises = AdvertisePeer::doSelectJoinAdvertiseCatalog($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AdvertisePeer::OWNER_ID, $this->id);

			if (!isset($this->lastAdvertiseCriteria) || !$this->lastAdvertiseCriteria->equals($criteria)) {
				$this->collAdvertises = AdvertisePeer::doSelectJoinAdvertiseCatalog($criteria, $con, $join_behavior);
			}
		}
		$this->lastAdvertiseCriteria = $criteria;

		return $this->collAdvertises;
	}

	/**
	 * Clears out the collOutgoingFundss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addOutgoingFundss()
	 */
	public function clearOutgoingFundss()
	{
		$this->collOutgoingFundss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collOutgoingFundss collection (array).
	 *
	 * By default this just sets the collOutgoingFundss collection to an empty array (like clearcollOutgoingFundss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initOutgoingFundss()
	{
		$this->collOutgoingFundss = array();
	}

	/**
	 * Gets an array of OutgoingFunds objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related OutgoingFundss from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array OutgoingFunds[]
	 * @throws     PropelException
	 */
	public function getOutgoingFundss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOutgoingFundss === null) {
			if ($this->isNew()) {
			   $this->collOutgoingFundss = array();
			} else {

				$criteria->add(OutgoingFundsPeer::USER_ID, $this->id);

				OutgoingFundsPeer::addSelectColumns($criteria);
				$this->collOutgoingFundss = OutgoingFundsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(OutgoingFundsPeer::USER_ID, $this->id);

				OutgoingFundsPeer::addSelectColumns($criteria);
				if (!isset($this->lastOutgoingFundsCriteria) || !$this->lastOutgoingFundsCriteria->equals($criteria)) {
					$this->collOutgoingFundss = OutgoingFundsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastOutgoingFundsCriteria = $criteria;
		return $this->collOutgoingFundss;
	}

	/**
	 * Returns the number of related OutgoingFunds objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related OutgoingFunds objects.
	 * @throws     PropelException
	 */
	public function countOutgoingFundss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collOutgoingFundss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(OutgoingFundsPeer::USER_ID, $this->id);

				$count = OutgoingFundsPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(OutgoingFundsPeer::USER_ID, $this->id);

				if (!isset($this->lastOutgoingFundsCriteria) || !$this->lastOutgoingFundsCriteria->equals($criteria)) {
					$count = OutgoingFundsPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collOutgoingFundss);
				}
			} else {
				$count = count($this->collOutgoingFundss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a OutgoingFunds object to this object
	 * through the OutgoingFunds foreign key attribute.
	 *
	 * @param      OutgoingFunds $l OutgoingFunds
	 * @return     void
	 * @throws     PropelException
	 */
	public function addOutgoingFunds(OutgoingFunds $l)
	{
		if ($this->collOutgoingFundss === null) {
			$this->initOutgoingFundss();
		}
		if (!in_array($l, $this->collOutgoingFundss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collOutgoingFundss, $l);
			$l->setUser($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this User is new, it will return
	 * an empty collection; or if this User has previously
	 * been saved, it will retrieve related OutgoingFundss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in User.
	 */
	public function getOutgoingFundssJoinAccount($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOutgoingFundss === null) {
			if ($this->isNew()) {
				$this->collOutgoingFundss = array();
			} else {

				$criteria->add(OutgoingFundsPeer::USER_ID, $this->id);

				$this->collOutgoingFundss = OutgoingFundsPeer::doSelectJoinAccount($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OutgoingFundsPeer::USER_ID, $this->id);

			if (!isset($this->lastOutgoingFundsCriteria) || !$this->lastOutgoingFundsCriteria->equals($criteria)) {
				$this->collOutgoingFundss = OutgoingFundsPeer::doSelectJoinAccount($criteria, $con, $join_behavior);
			}
		}
		$this->lastOutgoingFundsCriteria = $criteria;

		return $this->collOutgoingFundss;
	}

	/**
	 * Clears out the collStatAdvertDailys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addStatAdvertDailys()
	 */
	public function clearStatAdvertDailys()
	{
		$this->collStatAdvertDailys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collStatAdvertDailys collection (array).
	 *
	 * By default this just sets the collStatAdvertDailys collection to an empty array (like clearcollStatAdvertDailys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initStatAdvertDailys()
	{
		$this->collStatAdvertDailys = array();
	}

	/**
	 * Gets an array of StatAdvertDaily objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related StatAdvertDailys from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array StatAdvertDaily[]
	 * @throws     PropelException
	 */
	public function getStatAdvertDailys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collStatAdvertDailys === null) {
			if ($this->isNew()) {
			   $this->collStatAdvertDailys = array();
			} else {

				$criteria->add(StatAdvertDailyPeer::ADVERT_ID, $this->id);

				StatAdvertDailyPeer::addSelectColumns($criteria);
				$this->collStatAdvertDailys = StatAdvertDailyPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(StatAdvertDailyPeer::ADVERT_ID, $this->id);

				StatAdvertDailyPeer::addSelectColumns($criteria);
				if (!isset($this->lastStatAdvertDailyCriteria) || !$this->lastStatAdvertDailyCriteria->equals($criteria)) {
					$this->collStatAdvertDailys = StatAdvertDailyPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastStatAdvertDailyCriteria = $criteria;
		return $this->collStatAdvertDailys;
	}

	/**
	 * Returns the number of related StatAdvertDaily objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related StatAdvertDaily objects.
	 * @throws     PropelException
	 */
	public function countStatAdvertDailys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collStatAdvertDailys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(StatAdvertDailyPeer::ADVERT_ID, $this->id);

				$count = StatAdvertDailyPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(StatAdvertDailyPeer::ADVERT_ID, $this->id);

				if (!isset($this->lastStatAdvertDailyCriteria) || !$this->lastStatAdvertDailyCriteria->equals($criteria)) {
					$count = StatAdvertDailyPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collStatAdvertDailys);
				}
			} else {
				$count = count($this->collStatAdvertDailys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a StatAdvertDaily object to this object
	 * through the StatAdvertDaily foreign key attribute.
	 *
	 * @param      StatAdvertDaily $l StatAdvertDaily
	 * @return     void
	 * @throws     PropelException
	 */
	public function addStatAdvertDaily(StatAdvertDaily $l)
	{
		if ($this->collStatAdvertDailys === null) {
			$this->initStatAdvertDailys();
		}
		if (!in_array($l, $this->collStatAdvertDailys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collStatAdvertDailys, $l);
			$l->setUser($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this User is new, it will return
	 * an empty collection; or if this User has previously
	 * been saved, it will retrieve related StatAdvertDailys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in User.
	 */
	public function getStatAdvertDailysJoinAdvertise($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collStatAdvertDailys === null) {
			if ($this->isNew()) {
				$this->collStatAdvertDailys = array();
			} else {

				$criteria->add(StatAdvertDailyPeer::ADVERT_ID, $this->id);

				$this->collStatAdvertDailys = StatAdvertDailyPeer::doSelectJoinAdvertise($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(StatAdvertDailyPeer::ADVERT_ID, $this->id);

			if (!isset($this->lastStatAdvertDailyCriteria) || !$this->lastStatAdvertDailyCriteria->equals($criteria)) {
				$this->collStatAdvertDailys = StatAdvertDailyPeer::doSelectJoinAdvertise($criteria, $con, $join_behavior);
			}
		}
		$this->lastStatAdvertDailyCriteria = $criteria;

		return $this->collStatAdvertDailys;
	}

	/**
	 * Clears out the collStatAgentDailys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addStatAgentDailys()
	 */
	public function clearStatAgentDailys()
	{
		$this->collStatAgentDailys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collStatAgentDailys collection (array).
	 *
	 * By default this just sets the collStatAgentDailys collection to an empty array (like clearcollStatAgentDailys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initStatAgentDailys()
	{
		$this->collStatAgentDailys = array();
	}

	/**
	 * Gets an array of StatAgentDaily objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related StatAgentDailys from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array StatAgentDaily[]
	 * @throws     PropelException
	 */
	public function getStatAgentDailys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collStatAgentDailys === null) {
			if ($this->isNew()) {
			   $this->collStatAgentDailys = array();
			} else {

				$criteria->add(StatAgentDailyPeer::USER_ID, $this->id);

				StatAgentDailyPeer::addSelectColumns($criteria);
				$this->collStatAgentDailys = StatAgentDailyPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(StatAgentDailyPeer::USER_ID, $this->id);

				StatAgentDailyPeer::addSelectColumns($criteria);
				if (!isset($this->lastStatAgentDailyCriteria) || !$this->lastStatAgentDailyCriteria->equals($criteria)) {
					$this->collStatAgentDailys = StatAgentDailyPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastStatAgentDailyCriteria = $criteria;
		return $this->collStatAgentDailys;
	}

	/**
	 * Returns the number of related StatAgentDaily objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related StatAgentDaily objects.
	 * @throws     PropelException
	 */
	public function countStatAgentDailys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collStatAgentDailys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(StatAgentDailyPeer::USER_ID, $this->id);

				$count = StatAgentDailyPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(StatAgentDailyPeer::USER_ID, $this->id);

				if (!isset($this->lastStatAgentDailyCriteria) || !$this->lastStatAgentDailyCriteria->equals($criteria)) {
					$count = StatAgentDailyPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collStatAgentDailys);
				}
			} else {
				$count = count($this->collStatAgentDailys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a StatAgentDaily object to this object
	 * through the StatAgentDaily foreign key attribute.
	 *
	 * @param      StatAgentDaily $l StatAgentDaily
	 * @return     void
	 * @throws     PropelException
	 */
	public function addStatAgentDaily(StatAgentDaily $l)
	{
		if ($this->collStatAgentDailys === null) {
			$this->initStatAgentDailys();
		}
		if (!in_array($l, $this->collStatAgentDailys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collStatAgentDailys, $l);
			$l->setUser($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this User is new, it will return
	 * an empty collection; or if this User has previously
	 * been saved, it will retrieve related StatAgentDailys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in User.
	 */
	public function getStatAgentDailysJoinUserAdvertise($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collStatAgentDailys === null) {
			if ($this->isNew()) {
				$this->collStatAgentDailys = array();
			} else {

				$criteria->add(StatAgentDailyPeer::USER_ID, $this->id);

				$this->collStatAgentDailys = StatAgentDailyPeer::doSelectJoinUserAdvertise($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(StatAgentDailyPeer::USER_ID, $this->id);

			if (!isset($this->lastStatAgentDailyCriteria) || !$this->lastStatAgentDailyCriteria->equals($criteria)) {
				$this->collStatAgentDailys = StatAgentDailyPeer::doSelectJoinUserAdvertise($criteria, $con, $join_behavior);
			}
		}
		$this->lastStatAgentDailyCriteria = $criteria;

		return $this->collStatAgentDailys;
	}

	/**
	 * Clears out the collUserAdvertises collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserAdvertises()
	 */
	public function clearUserAdvertises()
	{
		$this->collUserAdvertises = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserAdvertises collection (array).
	 *
	 * By default this just sets the collUserAdvertises collection to an empty array (like clearcollUserAdvertises());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserAdvertises()
	{
		$this->collUserAdvertises = array();
	}

	/**
	 * Gets an array of UserAdvertise objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related UserAdvertises from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserAdvertise[]
	 * @throws     PropelException
	 */
	public function getUserAdvertises($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserAdvertises === null) {
			if ($this->isNew()) {
			   $this->collUserAdvertises = array();
			} else {

				$criteria->add(UserAdvertisePeer::USER_ID, $this->id);

				UserAdvertisePeer::addSelectColumns($criteria);
				$this->collUserAdvertises = UserAdvertisePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserAdvertisePeer::USER_ID, $this->id);

				UserAdvertisePeer::addSelectColumns($criteria);
				if (!isset($this->lastUserAdvertiseCriteria) || !$this->lastUserAdvertiseCriteria->equals($criteria)) {
					$this->collUserAdvertises = UserAdvertisePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserAdvertiseCriteria = $criteria;
		return $this->collUserAdvertises;
	}

	/**
	 * Returns the number of related UserAdvertise objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserAdvertise objects.
	 * @throws     PropelException
	 */
	public function countUserAdvertises(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserAdvertises === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserAdvertisePeer::USER_ID, $this->id);

				$count = UserAdvertisePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserAdvertisePeer::USER_ID, $this->id);

				if (!isset($this->lastUserAdvertiseCriteria) || !$this->lastUserAdvertiseCriteria->equals($criteria)) {
					$count = UserAdvertisePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collUserAdvertises);
				}
			} else {
				$count = count($this->collUserAdvertises);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UserAdvertise object to this object
	 * through the UserAdvertise foreign key attribute.
	 *
	 * @param      UserAdvertise $l UserAdvertise
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserAdvertise(UserAdvertise $l)
	{
		if ($this->collUserAdvertises === null) {
			$this->initUserAdvertises();
		}
		if (!in_array($l, $this->collUserAdvertises, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserAdvertises, $l);
			$l->setUser($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this User is new, it will return
	 * an empty collection; or if this User has previously
	 * been saved, it will retrieve related UserAdvertises from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in User.
	 */
	public function getUserAdvertisesJoinAdvertise($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserAdvertises === null) {
			if ($this->isNew()) {
				$this->collUserAdvertises = array();
			} else {

				$criteria->add(UserAdvertisePeer::USER_ID, $this->id);

				$this->collUserAdvertises = UserAdvertisePeer::doSelectJoinAdvertise($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserAdvertisePeer::USER_ID, $this->id);

			if (!isset($this->lastUserAdvertiseCriteria) || !$this->lastUserAdvertiseCriteria->equals($criteria)) {
				$this->collUserAdvertises = UserAdvertisePeer::doSelectJoinAdvertise($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserAdvertiseCriteria = $criteria;

		return $this->collUserAdvertises;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAccounts) {
				foreach ((array) $this->collAccounts as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collAdvertises) {
				foreach ((array) $this->collAdvertises as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collOutgoingFundss) {
				foreach ((array) $this->collOutgoingFundss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collStatAdvertDailys) {
				foreach ((array) $this->collStatAdvertDailys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collStatAgentDailys) {
				foreach ((array) $this->collStatAgentDailys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUserAdvertises) {
				foreach ((array) $this->collUserAdvertises as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAccounts = null;
		$this->collAdvertises = null;
		$this->collOutgoingFundss = null;
		$this->collStatAdvertDailys = null;
		$this->collStatAgentDailys = null;
		$this->collUserAdvertises = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseUser:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseUser::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseUser
