prod:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=adriva;host=192.168.8.18
      username:   adriva
      password:   ymPR4JPf 
      encoding:   utf8
      persistent: true
      pooling:    true

dev:
  propel:
    param:
      classname:  DebugPDO
      debug:
        realmemoryusage: true
        details:
          time:       { enabled: true }
          slow:       { enabled: true, threshold: 0.1 }
          mem:        { enabled: true } 
          mempeak:    { enabled: true }
          memdelta:   { enabled: true }

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=ADRRIVA;host=localhost
      username:   root
      password:   yfldjhtnhfdf 
      encoding:   utf8
      persistent: true
      pooling:    true
