<?php
// auto-generated by sfViewConfigHandler
// date: 2011/06/03 23:08:30
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('jquery-1.4.4.min.js', '', array ());
  $response->addJavascript('jquery.form.js', '', array ());
  $response->addJavascript('jquery.metadata.js', '', array ());
  $response->addJavascript('jquery.validate.js', '', array ());
  $response->addJavascript('messages_ru.js', '', array ());
  $response->addJavascript('jquery.simplemodal-1.4.1.js', '', array ());
  $response->addJavascript('jquery.flot.js', '', array ());


